import { Transaction } from "../../app/transactions/TransactionsTable";

export const mockTransactions: Transaction[] = [
  {
    id: "1",
    date: "2025-11-20",
    merchant: "Trader Joe's",
    category: "Groceries",
    account: "Checking",
    amount: -82.45,
  },
  {
    id: "2",
    date: "2025-11-19",
    merchant: "Rent",
    category: "Housing",
    account: "Checking",
    amount: -1200,
  },
  {
    id: "3",
    date: "2025-11-18",
    merchant: "Amazon",
    category: "Shopping",
    account: "Credit Card",
    amount: -45.2,
  },
  {
    id: "4",
    date: "2025-11-17",
    merchant: "Paycheck",
    category: "Income",
    account: "Checking",
    amount: 2100,
  },
  {
    id: "5",
    date: "2025-11-16",
    merchant: "Chipotle",
    category: "Dining",
    account: "Credit Card",
    amount: -14.5,
  },
  {
    id: "6",
    date: "2025-11-15",
    merchant: "Target",
    category: "Shopping",
    account: "Credit Card",
    amount: -56.33,
  },
  {
    id: "7",
    date: "2025-11-14",
    merchant: "Uber",
    category: "Transport",
    account: "Credit Card",
    amount: -18.92,
  },
  {
    id: "8",
    date: "2025-11-14",
    merchant: "Savings Transfer",
    category: "Transfer",
    account: "Checking",
    amount: -400,
  },
  {
    id: "9",
    date: "2025-11-13",
    merchant: "Savings Transfer",
    category: "Transfer",
    account: "Savings",
    amount: 400,
  },
  {
    id: "10",
    date: "2025-11-12",
    merchant: "Starbucks",
    category: "Dining",
    account: "Credit Card",
    amount: -6.75,
  },
];
